### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by ap2322** [philmccarthy/mod_0_skills#1]
Hi Phil, you performed well enough on the assessment to merit a chance to make some changes that can promote you to technical ready. Please make the following updates by EOD Sunday:

- [x] Your Menu class seems to use attributes and methods that don't specifically describe a menu and the actions that can be performed on or by it. For example, your `is_open` and `inventory` attributes and `open_store` and `restock` methods apply to an entire restaurant, not a menu. Update your Menu class to focus on a menu instead of an entire restaurant.
- [x] Edit the title of your [class_1_example_object](https://github.com/philmccarthy/mod_0_skills/blob/master/classes/class_1_example_object.md) to match the class you defined in [class_1](https://github.com/philmccarthy/mod_0_skills/blob/master/classes/class_1.md).
- [x] After you edit your Menu class, update the instance (example) of your menu so the methods show the specific values returned by performing that method on that particular instance. Use the [session 4 examples](https://mod0.turing.io/session4/#oop) as a guide.

**Comment by philmccarthy** [comment]
Thanks @ap2322. I've addressed these issues in today's commits.

**Comment by ap2322** [comment]
Phil this looks much better, you are officially `technical ready`! It's clear that you have a solid grasp of what we've taught in mod 0. Here's some feedback to keep in mind moving forward:
- Keep practicing the conceptual principles of OOP you learned in mod 0 - you'll be expanding on them, and using them to build more complex applications.
- Continue applying your detailed notice of syntax and practice your research skills of ruby methods - you did a great job with those on variables.txt!
- You did a great job with git workflow in this assessment - that skill will serve you well as you create and collaborate on more repos.
